version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: nightmarket-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: nightmarket
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d nightmarket']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  dbdata:
