name: Backend CI

on:
  push:
    paths:
      - "apps/backend/**"
      - ".github/workflows/backend-ci.yml"
  pull_request:
    paths:
      - "apps/backend/**"

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install deps (monorepo)
        run: pnpm install --frozen-lockfile

      - name: Lint (backend)
        working-directory: apps/backend
        run: pnpm lint

      - name: Unit tests
        working-directory: apps/backend
        run: pnpm test -- --ci

      - name: E2E tests
        working-directory: apps/backend
        run: pnpm test:e2e -- --ci

      - name: Coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: apps/backend/coverage
